name: Auto-close external PRs
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner.toLowerCase();
            const actor = context.actor.toLowerCase();
            if (actor !== owner) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.number,
                state: "closed"
              });
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                body: "Thanks for the interest! This repository isn’t accepting external PRs right now."
              });
            }
