name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  win-python:
    name: Windows • Python 3.13
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Normalize Git EOL (keep LF for .py/.yml/.md)
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Pip cache
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: pip-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip wheel

      # If you have a dev extra in pyproject:
      - name: Install (project + dev tools)
        run: |
          python -m pip install -e ".[dev]"
        continue-on-error: false

      # Fallback for repos without a dev extra:
      # - name: Install dev tools
      #   run: python -m pip install pre-commit ruff black mypy pytest

      - name: Pre-commit (ruff/black/mypy/etc.)
        run: pre-commit run --all-files

      - name: Pytest (fast suite)
        run: |
          python -m pytest -q -k "not slow and not e2e" --maxfail=1
